[package]
name = "macromusic"
version = "0.1.0"
authors = ["Pascal Hertleif <killercup@gmail.com>"]

[lib]
path = "lib.rs"

[[bin]]
name = "midimacro"
path = "main.rs"

[dependencies]
rodio = "0.6.0"
